### ISSUE TITLE
Top bar is still blank

### ISSUE THREAD

**Issue by jtlz2** [jtpio/jupyterlab-system-monitor#40] opened 2020-09-07 07:23 UTC
Hi -

I have pursued the installation instructions:

```
sudo -H pip install -U nbresuse==0.3.3
sudo jupyter labextension install jupyterlab-topbar-extension jupyterlab-system-monitor
```

followed by a browser refresh.

This still results in a blank top bar (except for grey bars either side).

Do I need to do a client-side reset application state?

Or do I need to do a server-side

```
sudo jupyter lab clean && sudo jupyter lab build
```

?

It would be great if you could help me get this over the line.

Many thanks in advance for all help!

PS Since I have no idea whether this is related to https://github.com/jtpio/jupyterlab-system-monitor/issues/28 or not I have opened a new ticket.

PPS I am running jupyterlab inside a docker container launched by jupyterhub on a kubernetes cluster.

PPPS Your excellent topbar extension does work - I can see the logout button, the light/dark theme switcher and the waving hand.

**Comment by jtpio** [comment] 2020-09-08 14:35
Thanks @jtlz2.

Which version of JupyterLab is it?

Also, does `jupyter labextension list` show any error?

**Comment by pedroprates** [comment] 2020-09-17 21:00
Same issue here. `jupyter labextension list` doesn't show any errors, `enabled OK`.

**Comment by sven5s** [comment] 2020-11-27 14:09
The issue is very general. So, I will leave a comment here instead of open a new issue.

I run Jupyter on Windows10 in a conda environment. Here are the important packages from conda list:
```
# Name                    Version                   Build  Channel
jupyter_core              4.7.0            py38haa244fe_0    conda-forge
jupyterlab                2.2.9                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
nodejs                    15.3.0               h57928b3_0    conda-forge
notebook                  6.1.5            py38haa244fe_0    conda-forge
psutil                    5.7.3            py38hab1e662_0    conda-forge
python                    3.8.6           h60c2a47_0_cpython    conda-forge
```
and my ~/.jupyter/jupyter_notebook_config.py
```
c = get_config()

# memory
c.NotebookApp.ResourceUseDisplay.mem_limit = 17179869184

# cpu
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
c.NotebookApp.ResourceUseDisplay.cpu_limit = 12
```
The advanced jupyterlab config is the system default.

In jupyter notebook I can see the memory consumption but not in jupyerlab. I also installed the theme-toggle and this works. So the topbar should also work. If I start jupyter lab with the debug flag I also can't see anything related with the system monitor.

Did I forget to configure something?

**Comment by dclong** [comment] 2020-12-20 04:42
I'm seeing a similar issue. I'm using JupyterLab 2.2.9. Below is the configuration object that printed out which shows that ResourceUseDisplay is indeed configured. But nothing is shown on the topbar. 

```
{'NotebookApp': {'ResourceUseDisplay': {'mem_limit': 6088820000, 'track_cpu_percent': True, 'cpu_limit': 4}}}
```

**Comment by dclong** [comment] 2020-12-20 08:15
BTW, I configured JupyterLab in /etc/jupyter instead of user's local settings dir. Does this work?

**Comment by jtpio** [comment] 2020-12-21 09:13
It should follow the list of directories returned by the `jupyter --paths` command. For example:

```bash
$ jupyter --paths
config:
    /home/username/miniforge3/envs/jupyterlab-system-monitor/etc/jupyter
    /home/username/.jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/username/miniforge3/envs/jupyterlab-system-monitor/share/jupyter
    /home/username/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/username/.local/share/jupyter/runtime
```


Also there has been a couple of changes on `nbresuse` recently which has been renamed to `jupyter-resource-usage`. Check the changelog for more details as the old `/metrics` endpoint has been deprecated and then removed, which could explain why the top bar appears to be blank: https://github.com/jupyter-server/jupyter-resource-usage/blob/master/CHANGELOG.md

We can add more info about these recent changes to the readme in this repo too, although it sounds like the best would be start moving the `jupyterlab-system-monitor` extension over to `jupyter-resource-usage` (https://github.com/jtpio/jupyterlab-system-monitor/issues/51).

**Comment by jabbera** [comment] 2021-04-24 03:09
I'm having this issue as well. Is there supposed to be an entry in the topbar config for this?

{
    // Top Bar Extension
    // jupyterlab-topbar-extension:plugin
    // Top Bar Extension
    // **********************************

    // Items Order
    // Ordered list of the Top Bar items
    "order": [
        "spacer",
        "memory"
    ]
}

**Comment by jtpio** [comment] 2023-07-28 14:32
Closing as `jupyterlab-system-monitor` has now been integrated in `jupyter-resource-usage`: https://github.com/jupyter-server/jupyter-resource-usage/issues/191

Feel free to open a new issue on the `jupyter-resource-usage` repo if needed: https://github.com/jupyter-server/jupyter-resource-usage

Thanks!

**Closed by jtpio** 2023-07-28 14:32 UTC
